[build]
  base = "FrontEnd" # Specify the directory containing your FrontEnd code
  command = "npm run build" # Adjust this command based on how you build your FrontEnd
  publish = "dist" # Specify the directory containing your built files (if applicable)
